version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-fix-path-2"
resolve_s3 = true
s3_prefix = "sam-app-fix-path-2"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
